# mkdir Command

- mkdir command in linux allows user to create or make new directories.
- mkdir stands for Make Directory
- With mkdir, you can also set permissions, create multiple directories (folders) at once, and much more.

### How to make a new directory in Linux
[source,bash]
----
$ mkdir aniket

Output:-
drwxrwxr-x. 2 centos centos 6 Sep 23 14:47 aniket
----

### How to create multiple directories with mkdir
[source,bash]
----
$ mkdir test devops admin OR mkdir {test,devops,admin}

[centos@ip-172-31-95-248 ~]$ ll
Output:-
drwxrwxr-x. 2 centos centos  6 Sep 23 15:10 admin
drwxrwxr-x. 2 centos centos  6 Sep 23 15:10 devops
drwxrwxr-x. 2 centos centos  6 Sep 23 15:10 test
----

### How to make a parent directory
[source,bash]
----
$ mkdir praj/wal
mkdir: cannot create directory ‘praj/wal’: No such file or directory

The above command throws an error because we havn't created praj directory
We have to use -p(parent directory) to create the nested directory at one time
For Eg.

$ mkdir -p praj/wal
[centos@ip-172-31-95-248 ~]$ ll
Output:-
drwxrwxr-x. 2 centos centos  6 Sep 23 14:47 aniket
drwxrwxr-x. 3 centos centos 17 Sep 23 15:03 praj
----

### How to set permissions while making a directory

To add rwx permissions to all the users, Use -m option
[source,bash]
$ mkdir -m752 analyst
[centos@ip-172-31-95-248 ~]$ ll
Output:-
drwxr-x-w-. 2 centos centos  6 Sep 23 15:22 analyst

# Copy Command

This command is use to copy file or group of files or directory

### Command to copy a file to the destination
[source,bash]
----
Syntax:-
cp file/directory-source destination

Command:-
$ cp abc.txt aniket/
----

### Command to copy a directory
[source,bash]
----
$ cp aniket/ admin/
cp: omitting directory ‘aniket/’

To copy file  or directory in recursive manner we use -r or -R oprion
$ cp -r aniket/ admin/
----

# Remove Command

This command is use to delete file or directory

### Command to delete file
[source,bash]
----
Syntax:-
$ rm <file name>

Command:-
$ rm abc.txt
----

### Command to remove the directory
[source,bash]
----
Syntax:-
rmdir <dir name> OR rm -r <dir name> OR  rm -rf <dir name>
-r = Recursively
-f = forcefully

Command:-
$ rmdir analyst/
----
