# ping Command

This command is use to check the status of other services
[source,bash]
----
Syntax:-
$ ping <hostname> / <IP Address>

Command:-
$ ping 8.8.8.8  OR  $ ping google.com

Output:-
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=50 time=0.566 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=50 time=0.660 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=50 time=0.641 ms
----

# hostname Command

This command is use to check the system hostname
[source,bash]
----
Syntax:-
$ hostname
----

### Command to check the private IP using hostname
[source,bash]
Command:-
$ hostname -i
Output:-
172.31.95.248

# telnet Command

This command is use to check if respective port is open/running or not

- When both port and services are open, it will shows connected 
[source,bash]
----
sudo yum install telnet -y
sudo yum install httpd -y
sudo systemctl start httpd

Syntax:-
$ telnet <private IP> <port number>

Command:-
$ telnet 172.31.95.248 80

Output:-
Trying 172.31.95.248...
Connected to 172.31.95.248.
----
- When port is open but service is closed, it will shows connection refused
[source,bash]
$ sudo systemctl stop  httpd
$ telnet 172.31.95.248 80
Output:- 
Trying 172.31.95.248...
telnet: connect to address 172.31.95.248: Connection refused

- When port is closed, it will shows trying....
[source,bash]
$ telnet 172.31.95.248 80
Output:- 
Trying 172.31.95.248...

# netstat Command [Network Statistics]

This command shows information about your network including statistics on connections,services ports and routing tables

[source,bash]
----
 Commands:-
 
 $ netstat
 $ netstat -apn [list all the unix ports]
 $ netstat -at [list all the tcp ports]
 $ netstat -au [list all the udp ports]
 $ netstat -lntpu [list all the tcp and udp ports]
----

# nslookup Command [name server lookup]

This command translates domain name to IP address and vice versa

### Install nslookup
[source,bash]
$ sudo yum install bind-utils

### Forward lookup
[source,bash]
$ nslookup 8.8.8.8 

### Reverse lookup
[source,bash]
----
$ nslookup google.com
Output:-
Server:         172.31.0.2
Address:        172.31.0.2#53*

Non-authoritative answer:
Name:   google.com
Address: 172.253.122.101
Name:   google.com
Address: 172.253.122.102
Name:   google.com
Address: 172.253.122.113
----
NOTE: #53 indicating that we are communicating with it on port 53 which is a standard port number of DNS use to accept queries

# dig Command [domain information groper]

This command is use to gather DNS information and it collects data about domain name server. Helpful for troubleshooting DNS problem
[source,bash]
$ dig google.com
